spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: admin
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/jizhangyl_instock?useUnicode=true&useSSL=false&autoReconnect=true
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      username: admin
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/jzgyl?useUnicode=true&useSSL=false&autoReconnect=true
  redis:
    host: 127.0.0.1
    port: 6379
wechat:
  notifyUrl: http://jizhangyl.natapp1.cc/jizhangyl/pay/notify
project-url:
  wechatOpenAuthorize: http://jizhangyl.natapp1.cc
  jizhangyl: http://jizhangyl.natapp1.cc
server:
  port: 8762